version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=novell@123
  insecurewebapp:
    image: "fortifydocker/iwa-dotnet:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=db;Database=aspnet-iwa-dev;User=sa;Password=novell@123;    
    build:
      context: .
      dockerfile: InsecureWebApp/Dockerfile
    ports:
    - "44331:80"
    depends_on:
      - db