# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

   # runs-on: ubuntu-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET / dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: |
        dotnet tool install --global dotnet-ef
        dotnet restore IWA.NET.sln
        dotnet tool restore 
       # dotnet ef database update
    - name: Build
      run: dotnet msbuild IWA.NET.sln /p:Configuration=Debug /t:Clean,Build
    #- name: Test
    #  run: dotnet test IWA.NET.sln --no-build --verbosity normal
